### ISSUE TITLE
Version Attribute Not Present

### ISSUE THREAD

**Issue by KevinCooper** [Squidly271/plugin-repository#1]
Attempting to install on UnRAID 6.6.6, and I'm getting the following error.

plugin: installing: https://raw.githubusercontent.com/Squidly271/plugin-repository/master/fix.common.problems.xml
plugin: downloading https://raw.githubusercontent.com/Squidly271/plugin-repository/master/fix.common.problems.xml
plugin: downloading: https://raw.githubusercontent.com/Squidly271/plugin-repository/master/fix.common.problems.xml ... done
plugin: version attribute not present

**Comment by Squidly271** [comment]
Install Community Applications, then install everything from there.  The xml isn't a .plg used to install.

**Comment by KevinCooper** [comment]
Thanks!
